services:
  queue:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin

    depends_on:
      - mongo